### ISSUE TITLE
get index of similar entries in the query result?

### ISSUE THREAD

**Issue by richardxy** [brandonrobertz/SparseLSH#4]
Hi,

Thanks very much for the wonderful package. Would you considering adding the index of similar entries into the result? Currently the result contains the vectors and the scores only. It'd be nice to know the row indices of the matched vectors.

thanks,
Richard

**Comment by brandonrobertz** [comment]
Hey, I'm not quite sure what you mean by "index". Are you referring to the index of the item as it is found in the hash "bucket/bin"? What are you trying to accomplish with this data?

Do you have code written? I'd like to take a look.

**Comment by richardxy** [comment]
Let me explain it using an example. I have a large sparse matrix, the rows of which are source IPs, and the columns are IPs that those source IPs have communication with. I want to find out the similar source IPs for a particular source IP. Currently I can get the rows of similar records, but I don't know which source IP that the returned data corresponds to. So I have to search the entire sparse matrix to find the row numbers, so that I would know their source IPs.  

That's one feature I wish to have. There is another feature which may also be very useful. Looking at this package https://github.com/go2starr/lshhdc/blob/master/lsh/lsh.py, I saw that it clusters high-dimension data based on the results of the LSH similarity. But they don't support sparse matrix, while you do. Would you consider implementing the clustering functionality based on the wonderful work you have already done?

Many thanks!
Richard

**Comment by brandonrobertz** [comment]
If each "column" represents one IP, can't you use the class-storage feature, so that when you pull similar entries, you also pull the class (IP) associated with it?

**Comment by brandonrobertz** [comment]
Closing this as there was no clarification or follow-up. Will re-open if this is still an issue.
