### ISSUE TITLE
Can I have fixed bucket size

### ISSUE THREAD

**Issue by Aashish1777** [brandonrobertz/SparseLSH#5]
Can we fix the size of buckets in your code? if yes what happens when buckets get full?

**Comment by brandonrobertz** [comment]
How would you define "full"? In LSH you typically want most of your buckets to have some items in them, preferably similar items. Can you elaborate?

**Comment by brandonrobertz** [comment]
If you wanted to fix a bucket size at, say, 5 then you'd pretty much need to hook into the insert command and check to see if a newly added item to a bucket reaches a certain size. Then you'd need to re-create and re-hash the entire dataset.

If you tried to resize the table and kept the existing buckets/clusters, there's no way to ensure that 1) your subsequent lookups would work and 2) that your items belong in the items they're now in.
